version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 783459136195.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker build -t ecs-html-app .
      - docker tag ecs-html-app:latest 783459136195.dkr.ecr.ap-south-1.amazonaws.com/ecs-html-app:latest

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 783459136195.dkr.ecr.ap-south-1.amazonaws.com/ecs-html-app:latest
      - printf '[{"name":"html-container","imageUri":"%s"}]' 783459136195.dkr.ecr.ap-south-1.amazonaws.com/ecs-html-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
